### ISSUE TITLE
Casos de poor performance del modelo

### ISSUE THREAD

**Issue by ankandrew** [ankandrew/cnn-ocr-lp#2]
Si notan que el modelo esta teniendo muy mala precisión en ciertos casos, pueden comentar aca para tratar de corregirlos.

Ejemplo, se clasifico erroneamente una N por una D y el 7 con el 1
![image](https://user-images.githubusercontent.com/61120139/92280543-fe481800-eecf-11ea-8c2c-2d043327fe85.png)

**Comment by diergui** [comment]
Hola! El algoritmo soporte imagenes tomadas de costado? buena definición, pero pensando en una persona parada atras del vehiculo sacando la fotografía de la pantente sin agacharse.

**Comment by ankandrew** [comment]
Una cámara elevada por ej. +10 metros de la posición del vehículo tranquilamente puede leer la patente. No hace falta que la cámara esta alineada al nivel de la patente.
