### ISSUE TITLE
Feature request: ONNX version

### ISSUE THREAD

**Issue by robinvanemden** [ankandrew/cnn-ocr-lp#3]
Just what I was looking for, a ConvNet-only LPR/OCR model - thanks for making it available!

For my purposes, it would be useful to be able to convert the Keras .h5 model to ONNX. But on conversion of any of the available models using [keras-onnx](https://github.com/onnx/keras-onnx), I encounter `ValueError: Unknown loss function: cce`.

Would it be possible for you to adapt your models to make them convertable to ONNX?

I don't know if it is of use, but an example keras to onnx Python conversion script can be downloaded [here](https://github.com/ankandrew/cnn-ocr-lp/files/6795213/keras2onnx.zip).

**Comment by ankandrew** [comment]
I just added a `onnx_converter.py`  to convert .h5 -> .onnx. I tried converting the following and worked:
`python onnx_converter.py --model models/m1_93_vpa_2.0M-i2.h5`
If think there is a bug with newer version of tensorflow and keras-onnx according to [this](https://github.com/onnx/keras-onnx/issues/662).

Let me know if there is any problem :)

**Comment by robinvanemden** [comment]
You are absolutely right! Thanks for you fast reply 👍
