### ISSUE TITLE
Implement the training in the other project

### ISSUE THREAD

**Issue by GiovannydaSilva** [ankandrew/cnn-ocr-lp#6]
After carrying out the training, is it possible to implement the model in the "ConvALPR" project? If yes, how?

**Comment by ankandrew** [comment]
@GiovannydaSilva Yes, change these references:
* https://github.com/ankandrew/ConvALPR/blob/b6dcbeba32df3f96099a00660bf8baaf7ed3f3d6/alpr/ocr.py#L97
* Add it here https://github.com/ankandrew/ConvALPR/blob/b6dcbeba32df3f96099a00660bf8baaf7ed3f3d6/alpr/ocr.py#L7

and make sure the saved model is in `alpr/models/ocr`
