### ISSUE TITLE
Difficulty converting the file generated by training

### ISSUE THREAD

**Issue by GiovannydaSilva** [ankandrew/cnn-ocr-lp#7]
The code generated by the training is in .h5 format, but in the ConvALPR project in the template directory there are .pb, .index and .data-00000-of-00001 format files. how do i convert the .h5 file to these three? I've been looking for a long time on the internet and I can't find how to do this...

**Comment by ankandrew** [comment]
Simply call `tf.keras.saving.save_model` w/o the `.h5` extension and will be saved in the [SavedModel format](https://www.tensorflow.org/guide/saved_model). See this https://colab.research.google.com/drive/1l_g-5by2LD23n9tMlLmKxTacFHhsxYLl?usp=sharing
