### ISSUE TITLE
Referencia

### ISSUE THREAD

**Issue by LautaroAndresSaez** [ankandrew/cnn-ocr-lp#8]
Hola, estamos utitlizando tu trabajo para una tesis de grado, y me gustaria saber si tenes algun paper, o si me podes para tu nombre para agregar a las referencias. Saludos!

**Comment by ankandrew** [comment]
Hola, no hay paper asociado a este repo, pero pueden citar directamente el repo con nombre de usuario de GitHub. Éxitos!!
